### ISSUE TITLE
panic on windows

### ISSUE THREAD

**Issue by 756445638** [timtadh/lexmachine#11]
GOROOT=D:\Go #gosetup
GOPATH=D:\gopath #gosetup
D:\Go\bin\go.exe build -o C:\Users\Administrator\AppData\Local\Temp\___compile.exe D:\gopath\src\github.com\756445638\lucy\src\cmd\compile\main.go #gosetup
"D:\Program Files\JetBrains\GoLand 2017.3\bin\runnerw.exe" C:\Users\Administrator\AppData\Local\Temp\___compile.exe #gosetup
panic: open /dev/urandom: The system cannot find the path specified.

goroutine 1 [running]:
github.com/timtadh/data-structures/set.init.0()
	D:/gopath/src/github.com/timtadh/data-structures/set/sortedset.go:18 +0x119
github.com/timtadh/data-structures/set.init()
	<autogenerated>:1 +0x78
github.com/timtadh/data-structures/linked.init()
	<autogenerated>:1 +0x69
github.com/timtadh/lexmachine/dfa.init()
	<autogenerated>:1 +0x5f
github.com/timtadh/lexmachine.init()
	<autogenerated>:1 +0x55
github.com/756445638/lucy/src/cmd/compile/lex.init()
	<autogenerated>:1 +0x57
github.com/756445638/lucy/src/cmd/compile/parser.init()
	<autogenerated>:1 +0x5c
github.com/756445638/lucy/src/cmd/compile/lc.init()
	<autogenerated>:1 +0x6b
main.init()
	<autogenerated>:1 +0x50

Process finished with exit code 2

seems on windows the file "/dev/urandom" dose not exist !!!
this library can not be used on windows??

**Comment by timtadh** [comment]
@756445638 sorry about that. This is an issue I had been meaning to get around to fixing in data-structures. I guess this bumps it up in importance: https://github.com/timtadh/data-structures/issues/4 . I will take a look as soon as I get a chance.

**Comment by timtadh** [comment]
@756445638 try using [v0.5.2](https://github.com/timtadh/data-structures/releases/tag/v0.5.2) of data-structures and seeing if that fixes this issue for you.

**Comment by timtadh** [comment]
assuming this fixes your problem. re-open or file a new ticket if you continue to have issues.

**Comment by 756445638** [comment]
ok,thank you

**Comment by timtadh** [comment]
no problem, good luck!
