### ISSUE TITLE
I use this as log parser, but the CPU pprof is ugly

### ISSUE THREAD

**Issue by duguying** [timtadh/lexmachine#30]
[pprof001.pdf](https://github.com/timtadh/lexmachine/files/2629059/pprof001.pdf)

I use this lexer as log parser. the CPU usage over 160%. the Sort method of your list cost so much time. could it has any solution for this problem.

**Comment by duguying** [comment]
it's my fault. i should not calling Compile every time when log line is coming. just call Compile once. and then reuse the scanner. thanks.

**Comment by timtadh** [comment]
Glad moving the compile to a onetime operation solved your performance problems. If you have further problems I have some ideas about further performance improvements but I have essentially been waiting for user needs before implementing them. Consider joining the mailing list for version announcements. Thanks for opening an issue.
