### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by gotmax23** [timtadh/lexmachine#39]
This package is BSD-3-Clause licensed, but it depends on github.com/timtadh/data-structures which is (mostly) licensed under GPL-2.0-only. Wouldn't that mean that any projects that depend on this module would also need to be licensed under GPL-2.0-only? Can you please clarify this situation and consider re-licensing github.com/timtadh/data-structures under a compatible license?

**Comment by timtadh** [comment]
@gotmax23 please reach out to me via email about you specific needs.

**Comment by timtadh** [comment]
After a little back and forth this is resolved. github.com/timtadh/data-structures is BSD 3-clause as of version v0.6.1 and lexmachine has been updated to use it as of v0.2.3
